name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # ⚠️ Asegúrate de que tu rama principal se llame main (o cámbialo a master)

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
 
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Versión estable de Node para compilar
          cache: 'pnpm'

      - name: Build
        run: pnpm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite guarda todo en 'dist'
          branch: gh-pages # La rama donde se subirá la web compilada